(in-package #:xml-backend-native)

(defun xml-escape (string &key attr)
  (with-output-to-string (s)
    (loop for c across string
          do (case c
               (#\& (write-string "&amp;" s))
               (#\< (write-string "&lt;" s))
               (#\> (write-string "&gt;" s))
               (#\" (write-string (if attr "&quot;" "\"") s))
               (t (write-char c s))))))

(defun %write-indent (stream n)
  (dotimes (i n)
    (write-string "  " stream)))

(defun %write-attrs (stream attrs)
  (dolist (a attrs)
    (write-char #\Space stream)
    (write-string (xml-qname a) stream)
    (write-string "=\"" stream)
    (write-string (xml-escape (xml-attribute-value a) :attr t) stream)
    (write-char #\" stream)))

(defun %write-element (el stream pretty indent)
  (when pretty (%write-indent stream indent))
  (write-char #\< stream)
  (write-string (xml-qname el) stream)
  (%write-attrs stream (xml-element-attributes el))
  (let ((kids (xml-element-children el)))
    (cond
      ((null kids)
       (write-string "/>" stream)
       (when pretty (write-char #\Newline stream)))
      ((and (= 1 (length kids))
            (or (xml-text-p (first kids)) (stringp (first kids)))
            (not pretty))
       (write-char #\> stream)
       (write-string (xml-escape (if (stringp (first kids))
                                     (first kids)
                                     (xml-text-data (first kids))))
                     stream)
       (write-string "</" stream)
       (write-string (xml-qname el) stream)
       (write-string ">" stream))
      ((and (= 1 (length kids))
            (or (xml-text-p (first kids)) (stringp (first kids))))
       (write-char #\> stream)
       (write-string (xml-escape (if (stringp (first kids))
                                     (first kids)
                                     (xml-text-data (first kids))))
                     stream)
       (write-string "</" stream)
       (write-string (xml-qname el) stream)
       (write-string ">" stream)
       (write-char #\Newline stream))
      (t
       (write-char #\> stream)
       (when pretty (write-char #\Newline stream))
       (dolist (k kids)
         (%write-node k stream pretty (1+ indent)))
       (when pretty (%write-indent stream indent))
       (write-string "</" stream)
       (write-string (xml-qname el) stream)
       (write-string ">" stream)
       (when pretty (write-char #\Newline stream))))))

(defun %write-node (node stream pretty indent)
  (cond
    ((xml-element-p node)
     (%write-element node stream pretty indent))
    ((xml-text-p node)
     (when pretty (%write-indent stream indent))
     (write-string (xml-escape (xml-text-data node)) stream)
     (when pretty (write-char #\Newline stream)))
    ((stringp node)
     (when pretty (%write-indent stream indent))
     (write-string (xml-escape node) stream)
     (when pretty (write-char #\Newline stream)))
    ((xml-cdata-p node)
     (when pretty (%write-indent stream indent))
     (write-string "<![CDATA[" stream)
     (write-string (xml-cdata-data node) stream)
     (write-string "]]>" stream)
     (when pretty (write-char #\Newline stream)))
    ((xml-comment-p node)
     (when pretty (%write-indent stream indent))
     (write-string "<!--" stream)
     (write-string (xml-comment-data node) stream)
     (write-string "-->" stream)
     (when pretty (write-char #\Newline stream)))
    ((xml-pi-p node)
     (when pretty (%write-indent stream indent))
     (write-string "<?" stream)
     (write-string (xml-pi-target node) stream)
     (when (plusp (length (xml-pi-data node)))
       (write-char #\Space stream)
       (write-string (xml-pi-data node) stream))
     (write-string "?>" stream)
     (when pretty (write-char #\Newline stream)))
    ((xml-doctype-p node)
     (when pretty (%write-indent stream indent))
     (write-string "<!DOCTYPE " stream)
     (write-string (xml-doctype-name node) stream)
     (when (xml-doctype-public-id node)
       (write-string " PUBLIC \"" stream)
       (write-string (xml-doctype-public-id node) stream)
       (write-char #\" stream)
       (when (xml-doctype-system-id node)
         (write-string " \"" stream)
         (write-string (xml-doctype-system-id node) stream)
         (write-char #\" stream)))
     (when (and (xml-doctype-system-id node) (not (xml-doctype-public-id node)))
       (write-string " SYSTEM \"" stream)
       (write-string (xml-doctype-system-id node) stream)
       (write-char #\" stream))
     (write-string ">" stream)
     (when pretty (write-char #\Newline stream)))))

(defun write-xml (value stream &key (pretty t) (declaration t))
  (let ((doc (cond
               ((xml-document-p value) value)
               ((xml-element-p value)
                (make-xml-document :children (list value)))
               (t (error 'xml-encode-error
                         :message (format nil "cannot encode ~S" (type-of value)))))))
    (when declaration
      (format stream "<?xml version=\"~A\" encoding=\"~A\"~@[ standalone=\"yes\"~]?>"
              (or (xml-document-version doc) "1.0")
              (or (xml-document-encoding doc) "UTF-8")
              (xml-document-standalone doc))
      (write-char #\Newline stream))
    (dolist (c (xml-document-children doc))
      (%write-node c stream pretty 0))
    (values)))

(defclass native-event-writer (xml-event-writer)
  ((pretty :initarg :pretty :reader %writer-pretty)
   (declaration :initarg :declaration :reader %writer-declaration)
   (started :initform nil :accessor %writer-started)
   (stack :initform nil :accessor %writer-stack)))

(defun %ensure-decl (writer)
  (unless (%writer-started writer)
    (setf (%writer-started writer) t)
    (when (%writer-declaration writer)
      (write-string "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
                    (event-writer-stream writer))
      (write-char #\Newline (event-writer-stream writer)))))

(defmethod write-event ((writer native-event-writer) event &optional value)
  (let ((stream (event-writer-stream writer))
        (pretty (%writer-pretty writer)))
    (when (xml-element-p event)
      (%ensure-decl writer)
      (%write-element event stream pretty (length (%writer-stack writer)))
      (return-from write-event event))
    (ecase event
      (:start-document
       (%ensure-decl writer))
      (:end-document
       (values))
      (:dtd
       (%ensure-decl writer)
       (%write-node value stream pretty 0))
      (:start-element
       (%ensure-decl writer)
       (let ((indent (length (%writer-stack writer))))
         (when pretty (%write-indent stream indent))
         (write-char #\< stream)
         (write-string (xml-qname value) stream)
         (%write-attrs stream (xml-element-attributes value))
         (write-char #\> stream)
         (when pretty (write-char #\Newline stream)))
       (push value (%writer-stack writer)))
      (:end-element
       (let ((el (or value (pop (%writer-stack writer)))))
         (when (and value (%writer-stack writer)
                    (eq (first (%writer-stack writer)) value))
           (pop (%writer-stack writer)))
         (when (and (null value) (null el))
           (error 'xml-encode-error :message "end-element with empty stack"))
         (when (and value (not (eq el value)) (%writer-stack writer))
           (pop (%writer-stack writer)))
         (let ((indent (length (%writer-stack writer))))
           (when pretty (%write-indent stream indent))
           (write-string "</" stream)
           (write-string (xml-qname (or el value)) stream)
           (write-string ">" stream)
           (when pretty (write-char #\Newline stream)))))
      (:characters
       (%ensure-decl writer)
       (%write-node (if (or (xml-text-p value) (xml-cdata-p value))
                        value
                        (make-instance 'xml-text :data (princ-to-string value)))
                    stream pretty (length (%writer-stack writer))))
      (:comment
       (%ensure-decl writer)
       (%write-node (if (xml-comment-p value)
                        value
                        (make-instance 'xml-comment :data (princ-to-string value)))
                    stream pretty (length (%writer-stack writer))))
      (:processing-instruction
       (%ensure-decl writer)
       (%write-node value stream pretty (length (%writer-stack writer))))))
  value)
